# Generated by Django 5.1 on 2024-12-11 09:20

import datetime
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('add', models.TextField(default='')),
                ('Email', models.EmailField(default='', help_text='enter your email :', max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('confirm_password', models.CharField(max_length=8)),
                ('date', models.DateField(default=datetime.datetime(2024, 12, 11, 14, 50, 2, 60534))),
                ('Time', models.TimeField(default=datetime.datetime(2024, 12, 11, 14, 50, 2, 60534))),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('photo', models.FileField(upload_to='')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
    ]
