# Generated by Django 5.1 on 2024-12-13 09:06

import datetime
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField(default=18)),
                ('Address', models.TextField(default='')),
                ('Email', models.EmailField(default='', help_text='enter your email :', max_length=254)),
                ('Mobile', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=8)),
                ('Confirm_Password', models.CharField(max_length=8)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Time', models.TimeField(default=django.utils.timezone.now)),
                ('Birth_Date', models.DateField(default=datetime.datetime.now)),
                ('File', models.FileField(upload_to='')),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('Country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('State', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisghar', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh')], max_length=17)),
                ('City', models.CharField(blank=True, choices=[('AHMADABAD', 'AHMADABAD'), ('AMARELI', 'AMRELI'), ('ANAND', 'ANAND'), ('BANASKATHA', 'BANSKATHA'), ('BHARUCH', 'BHARUCH'), ('BHAVNAGAR', 'BHAVNAGAR'), ('DAHOD', 'DAHOD'), ('DANG', 'DANG'), ('GANDINAGAR', 'GANDHINAGAR'), ('JAMNAGAR', 'JAMNAGAR'), ('JUNAGADH', 'JUNAGADH'), ('KACHHBHUJ', 'KACHCHHBHUJ'), ('KHEDA', 'KHEDA'), ('MAHESANA', 'MAHESANA'), ('NARMADA', 'NARMADA'), ('NAVSARI', 'NAVSARI'), ('PANCHMAHAL', 'PANCHMAHAL'), ('PATAN', 'PATAN'), ('PORBANDAR', 'PORBANDAR'), ('RAJKOT', 'RAJKOT'), ('SABARKATHA', 'SABARKATHA'), ('SURAT', 'SURAT'), ('SURENDRAGAR', 'SURENDRANAGR'), ('TAPI', 'TAPI'), ('VADODRA', 'VADODRA'), ('VALSAD', 'VALSAD')], max_length=11)),
            ],
        ),
    ]
