# Generated by Django 5.1 on 2024-12-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='File',
        ),
    ]
