# Generated by Django 5.1 on 2024-12-11 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2024, 12, 11, 14, 37, 4, 55179)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 14, 37, 4, 55179)),
        ),
    ]
