# Generated by Django 5.1 on 2024-12-11 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_student_state_alter_student_time_alter_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, choices=[('A', 'AHMADABAD')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2024, 12, 11, 16, 32, 35, 739509)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 16, 32, 35, 739509)),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, choices=[('A', 'Andhra Pradesh'), ('A', 'Arunachal Pradesh'), ('A', 'Assam'), ('B', 'Bihar'), ('C', 'Chhattisgarh'), ('D', 'Delhi'), ('G', 'Goa'), ('G', 'Gujarat'), ('H', 'Haryana'), ('H', 'Himachal Pradesh'), ('J', 'Jharkhand'), ('K', 'Karnataka'), ('K', 'Kerala'), ('M', 'Madhya Pradesh'), ('M', 'Maharashtra'), ('M', 'Manipur'), ('M', 'Meghalaya'), ('M', 'Mizoram'), ('M', 'Nagaland'), ('O', 'Odisha'), ('P', 'Punjab'), ('R', 'Rajasthan'), ('S', 'Sikkim'), ('T', '1Tamil Nadu'), ('T', 'Telangana'), ('T', 'Tripura'), ('U', 'Uttar Pradesh')], max_length=1),
        ),
    ]
