# Generated by Django 5.1 on 2024-12-11 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_student_city_alter_student_time_alter_student_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2024, 12, 11, 16, 36, 39, 524877)),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, choices=[('A', 'AHMADABAD'), ('A', 'AMRELI'), ('A', 'ANAND'), ('B', 'BANSKATHA'), ('B', 'BHARUCH'), ('B', 'BHAVNAGAR'), ('D', 'DAHOD'), ('D', 'DANG'), ('G', 'GANDHINAGAR'), ('J', 'JAMNAGAR'), ('J', 'JUNAGADH'), ('K', 'KACHCHHBHUJ'), ('K', 'KHEDA'), ('M', 'MAHESANA'), ('N', 'NARMADA'), ('N', 'NAVSARI'), ('P', 'PANCHMAHAL'), ('P', 'PATAN'), ('P', 'PORBANDAR'), ('R', 'RAJKOT'), ('S', 'SABARKATHA'), ('S', 'SURAT'), ('S', 'SURENDRANAGR'), ('T', 'TAPI'), ('V', 'VADODRA'), ('V', 'VALSAD')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 16, 36, 39, 524877)),
        ),
    ]
